spring:
  datasource:
    url: jdbc:h2:mem:dentist_test_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

springdoc:
  swagger-ui:
    path: /swagger.html