spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate.ddl-auto: create

springdoc:
  swagger-ui:
    path: /swagger.html